# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from lerobot_robot_grpc.protos import device_pb2 as lerobot__robot__grpc_dot_protos_dot_device__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in lerobot_robot_grpc/protos/device_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RobotStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInfo = channel.unary_unary(
                '/rdc.v1.Robot/GetInfo',
                request_serializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.GetInfoRequest.SerializeToString,
                response_deserializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.GetInfoResponse.FromString,
                _registered_method=True)
        self.Connect = channel.unary_unary(
                '/rdc.v1.Robot/Connect',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.CalibrationInfo.FromString,
                _registered_method=True)
        self.Calibrate = channel.unary_unary(
                '/rdc.v1.Robot/Calibrate',
                request_serializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.CalibrateRequest.SerializeToString,
                response_deserializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.CalibrationInfo.FromString,
                _registered_method=True)
        self.CalibrateDone = channel.unary_unary(
                '/rdc.v1.Robot/CalibrateDone',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.StreamCalibration = channel.unary_stream(
                '/rdc.v1.Robot/StreamCalibration',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.CalibrationFrame.FromString,
                _registered_method=True)
        self.Disconnect = channel.unary_unary(
                '/rdc.v1.Robot/Disconnect',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetObservation = channel.unary_stream(
                '/rdc.v1.Robot/GetObservation',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.OneFeature.FromString,
                _registered_method=True)
        self.SendAction = channel.unary_unary(
                '/rdc.v1.Robot/SendAction',
                request_serializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.Action.SerializeToString,
                response_deserializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.ActionResult.FromString,
                _registered_method=True)
        self.GetFeedback = channel.unary_stream(
                '/rdc.v1.Robot/GetFeedback',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.OneFeature.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/rdc.v1.Robot/GetStatus',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.DeviceInfo.FromString,
                _registered_method=True)
        self.SetReference = channel.unary_unary(
                '/rdc.v1.Robot/SetReference',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Hold = channel.unary_unary(
                '/rdc.v1.Robot/Hold',
                request_serializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.HoldRequest.SerializeToString,
                response_deserializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.HoldResponse.FromString,
                _registered_method=True)
        self.Resume = channel.unary_unary(
                '/rdc.v1.Robot/Resume',
                request_serializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.ResumeRequest.SerializeToString,
                response_deserializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.ResumeResponse.FromString,
                _registered_method=True)


class RobotServicer:
    """Missing associated documentation comment in .proto file."""

    def GetInfo(self, request, context):
        """schema 一次性协商(替代三个 Get*FeatureInfo)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Connect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Calibrate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalibrateDone(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamCalibration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Disconnect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetObservation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendAction(self, request, context):
        """unary:请求=commanded,响应=executed(不再是 fire-and-forget 的 stream→Empty)。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFeedback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetReference(self, request, context):
        """把当前末端 FK 重锁为 pose_delta 基准 T_zero(与 Teleoperator.SetReference 对偶)。
        离合器再接合时客户端先调本 RPC 再调 leader SetReference,保证"当前手=当前臂"。
        不支持 pose_delta 的 follower 返回 UNIMPLEMENTED。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Hold(self, request, context):
        """Fail-closed session gate used by collection orchestration during
        tracker loss, manual clutch, alignment, and emergency handling.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Resume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInfo,
                    request_deserializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.GetInfoRequest.FromString,
                    response_serializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.GetInfoResponse.SerializeToString,
            ),
            'Connect': grpc.unary_unary_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.CalibrationInfo.SerializeToString,
            ),
            'Calibrate': grpc.unary_unary_rpc_method_handler(
                    servicer.Calibrate,
                    request_deserializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.CalibrateRequest.FromString,
                    response_serializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.CalibrationInfo.SerializeToString,
            ),
            'CalibrateDone': grpc.unary_unary_rpc_method_handler(
                    servicer.CalibrateDone,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'StreamCalibration': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamCalibration,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.CalibrationFrame.SerializeToString,
            ),
            'Disconnect': grpc.unary_unary_rpc_method_handler(
                    servicer.Disconnect,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetObservation': grpc.unary_stream_rpc_method_handler(
                    servicer.GetObservation,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.OneFeature.SerializeToString,
            ),
            'SendAction': grpc.unary_unary_rpc_method_handler(
                    servicer.SendAction,
                    request_deserializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.Action.FromString,
                    response_serializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.ActionResult.SerializeToString,
            ),
            'GetFeedback': grpc.unary_stream_rpc_method_handler(
                    servicer.GetFeedback,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.OneFeature.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.DeviceInfo.SerializeToString,
            ),
            'SetReference': grpc.unary_unary_rpc_method_handler(
                    servicer.SetReference,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Hold': grpc.unary_unary_rpc_method_handler(
                    servicer.Hold,
                    request_deserializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.HoldRequest.FromString,
                    response_serializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.HoldResponse.SerializeToString,
            ),
            'Resume': grpc.unary_unary_rpc_method_handler(
                    servicer.Resume,
                    request_deserializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.ResumeRequest.FromString,
                    response_serializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.ResumeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rdc.v1.Robot', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rdc.v1.Robot', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Robot:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rdc.v1.Robot/GetInfo',
            lerobot__robot__grpc_dot_protos_dot_device__pb2.GetInfoRequest.SerializeToString,
            lerobot__robot__grpc_dot_protos_dot_device__pb2.GetInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rdc.v1.Robot/Connect',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            lerobot__robot__grpc_dot_protos_dot_device__pb2.CalibrationInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Calibrate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rdc.v1.Robot/Calibrate',
            lerobot__robot__grpc_dot_protos_dot_device__pb2.CalibrateRequest.SerializeToString,
            lerobot__robot__grpc_dot_protos_dot_device__pb2.CalibrationInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalibrateDone(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rdc.v1.Robot/CalibrateDone',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamCalibration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rdc.v1.Robot/StreamCalibration',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            lerobot__robot__grpc_dot_protos_dot_device__pb2.CalibrationFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Disconnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rdc.v1.Robot/Disconnect',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetObservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rdc.v1.Robot/GetObservation',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            lerobot__robot__grpc_dot_protos_dot_device__pb2.OneFeature.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rdc.v1.Robot/SendAction',
            lerobot__robot__grpc_dot_protos_dot_device__pb2.Action.SerializeToString,
            lerobot__robot__grpc_dot_protos_dot_device__pb2.ActionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rdc.v1.Robot/GetFeedback',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            lerobot__robot__grpc_dot_protos_dot_device__pb2.OneFeature.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rdc.v1.Robot/GetStatus',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            lerobot__robot__grpc_dot_protos_dot_device__pb2.DeviceInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetReference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rdc.v1.Robot/SetReference',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Hold(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rdc.v1.Robot/Hold',
            lerobot__robot__grpc_dot_protos_dot_device__pb2.HoldRequest.SerializeToString,
            lerobot__robot__grpc_dot_protos_dot_device__pb2.HoldResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Resume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rdc.v1.Robot/Resume',
            lerobot__robot__grpc_dot_protos_dot_device__pb2.ResumeRequest.SerializeToString,
            lerobot__robot__grpc_dot_protos_dot_device__pb2.ResumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TeleoperatorStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInfo = channel.unary_unary(
                '/rdc.v1.Teleoperator/GetInfo',
                request_serializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.GetInfoRequest.SerializeToString,
                response_deserializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.GetInfoResponse.FromString,
                _registered_method=True)
        self.Connect = channel.unary_unary(
                '/rdc.v1.Teleoperator/Connect',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.CalibrationInfo.FromString,
                _registered_method=True)
        self.Calibrate = channel.unary_unary(
                '/rdc.v1.Teleoperator/Calibrate',
                request_serializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.CalibrateRequest.SerializeToString,
                response_deserializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.CalibrationInfo.FromString,
                _registered_method=True)
        self.CalibrateDone = channel.unary_unary(
                '/rdc.v1.Teleoperator/CalibrateDone',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.StreamCalibration = channel.unary_stream(
                '/rdc.v1.Teleoperator/StreamCalibration',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.CalibrationFrame.FromString,
                _registered_method=True)
        self.Disconnect = channel.unary_unary(
                '/rdc.v1.Teleoperator/Disconnect',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetObservation = channel.unary_stream(
                '/rdc.v1.Teleoperator/GetObservation',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.OneFeature.FromString,
                _registered_method=True)
        self.GetAction = channel.unary_stream(
                '/rdc.v1.Teleoperator/GetAction',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.OneFeature.FromString,
                _registered_method=True)
        self.SendFeedback = channel.stream_unary(
                '/rdc.v1.Teleoperator/SendFeedback',
                request_serializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.OneFeature.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/rdc.v1.Teleoperator/GetStatus',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.DeviceInfo.FromString,
                _registered_method=True)
        self.GetTrackingReadiness = channel.unary_unary(
                '/rdc.v1.Teleoperator/GetTrackingReadiness',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.TrackingReadiness.FromString,
                _registered_method=True)
        self.SetReference = channel.unary_unary(
                '/rdc.v1.Teleoperator/SetReference',
                request_serializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.SetReferenceRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class TeleoperatorServicer:
    """Missing associated documentation comment in .proto file."""

    def GetInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Connect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Calibrate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalibrateDone(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamCalibration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Disconnect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetObservation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendFeedback(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrackingReadiness(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetReference(self, request, context):
        """锁定当前位姿为基准;之后 GetAction 输出相对该基准的 delta(A 类 engage 协议)。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TeleoperatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInfo,
                    request_deserializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.GetInfoRequest.FromString,
                    response_serializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.GetInfoResponse.SerializeToString,
            ),
            'Connect': grpc.unary_unary_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.CalibrationInfo.SerializeToString,
            ),
            'Calibrate': grpc.unary_unary_rpc_method_handler(
                    servicer.Calibrate,
                    request_deserializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.CalibrateRequest.FromString,
                    response_serializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.CalibrationInfo.SerializeToString,
            ),
            'CalibrateDone': grpc.unary_unary_rpc_method_handler(
                    servicer.CalibrateDone,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'StreamCalibration': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamCalibration,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.CalibrationFrame.SerializeToString,
            ),
            'Disconnect': grpc.unary_unary_rpc_method_handler(
                    servicer.Disconnect,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetObservation': grpc.unary_stream_rpc_method_handler(
                    servicer.GetObservation,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.OneFeature.SerializeToString,
            ),
            'GetAction': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAction,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.OneFeature.SerializeToString,
            ),
            'SendFeedback': grpc.stream_unary_rpc_method_handler(
                    servicer.SendFeedback,
                    request_deserializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.OneFeature.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.DeviceInfo.SerializeToString,
            ),
            'GetTrackingReadiness': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrackingReadiness,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.TrackingReadiness.SerializeToString,
            ),
            'SetReference': grpc.unary_unary_rpc_method_handler(
                    servicer.SetReference,
                    request_deserializer=lerobot__robot__grpc_dot_protos_dot_device__pb2.SetReferenceRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rdc.v1.Teleoperator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rdc.v1.Teleoperator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Teleoperator:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rdc.v1.Teleoperator/GetInfo',
            lerobot__robot__grpc_dot_protos_dot_device__pb2.GetInfoRequest.SerializeToString,
            lerobot__robot__grpc_dot_protos_dot_device__pb2.GetInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rdc.v1.Teleoperator/Connect',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            lerobot__robot__grpc_dot_protos_dot_device__pb2.CalibrationInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Calibrate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rdc.v1.Teleoperator/Calibrate',
            lerobot__robot__grpc_dot_protos_dot_device__pb2.CalibrateRequest.SerializeToString,
            lerobot__robot__grpc_dot_protos_dot_device__pb2.CalibrationInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalibrateDone(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rdc.v1.Teleoperator/CalibrateDone',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamCalibration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rdc.v1.Teleoperator/StreamCalibration',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            lerobot__robot__grpc_dot_protos_dot_device__pb2.CalibrationFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Disconnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rdc.v1.Teleoperator/Disconnect',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetObservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rdc.v1.Teleoperator/GetObservation',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            lerobot__robot__grpc_dot_protos_dot_device__pb2.OneFeature.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rdc.v1.Teleoperator/GetAction',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            lerobot__robot__grpc_dot_protos_dot_device__pb2.OneFeature.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendFeedback(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/rdc.v1.Teleoperator/SendFeedback',
            lerobot__robot__grpc_dot_protos_dot_device__pb2.OneFeature.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rdc.v1.Teleoperator/GetStatus',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            lerobot__robot__grpc_dot_protos_dot_device__pb2.DeviceInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrackingReadiness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rdc.v1.Teleoperator/GetTrackingReadiness',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            lerobot__robot__grpc_dot_protos_dot_device__pb2.TrackingReadiness.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetReference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rdc.v1.Teleoperator/SetReference',
            lerobot__robot__grpc_dot_protos_dot_device__pb2.SetReferenceRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
